INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (1, 'PLAT', 'PLATEADO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/009.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (2, 'ACOR', 'CORAZÓN', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/316.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (3, 'BGAF', 'GAFAS', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/317.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (4, 'CGUÑ', 'GUIÑO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/318.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (5, 'DSON', 'SONRISA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/319.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (6, 'AMA', 'AMARILLO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/005.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (7, 'AZUL', 'AZUL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/019.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (8, 'NATU', 'NATURAL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/013.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (9, 'ROJ', 'ROJO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/003.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (10, 'BLA', 'BLANCO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/001.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (11, 'NEG', 'NEGRO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/002.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (12, 'VER', 'VERDE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/004.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (13, 'NARA', 'NARANJA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/007.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (14, 'ROSA', 'ROSA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/022.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (15, 'MAR', 'MARINO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/006.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (16, 'FUCSI', 'FUCSIA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/011.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (17, 'TRANS', 'TRANSPARENTE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/216.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (18, 'VEC', 'VERDE CLARO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/279.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (19, 'GRI', 'GRIS', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/008.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (20, 'MARR', 'MARRON', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/018.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (21, 'AZC', 'AZUL CLARO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/021.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (22, 'BUR', 'BURDEOS', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/020.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (23, 'BEI', 'BEIG', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/117.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (24, 'KAK', 'KHAKI', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/014.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (25, 'ESP', 'ESPAÑA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/139.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (26, 'BLAZ', 'BLANCO / AZUL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/119.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (27, 'BLNA', 'BLANCO / NARANJA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/123.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (28, 'BLRO', 'BLANCO / ROJO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/125.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (29, 'BLVE', 'BLANCO / VERDE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/126.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (30, 'DOR', 'DORADO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/023.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (31, 'A', 'TIPO A', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/100.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (32, 'B', 'TIPO B', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/115.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (33, 'C', 'TIPO C', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/128.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (34, 'LIMA', 'LIMA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/284.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (35, 'MACL', 'MARRÓN CLARO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/162.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (36, 'MAOS', 'MARRÓN OSCURO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/167.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (37, 'NGGR', 'NEGRO / GRIS', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/195.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (38, 'LIMON', 'LIMON', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/158.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (39, 'SAND', 'SANDIA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/261.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (40, 'AZR', 'AZUL ROYAL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/228.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (41, 'BLFU', 'BLANCO / FUCSIA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/120.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (42, 'NEBL', 'NEGRO/BLANCO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/192.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (43, 'BGOL', 'GOLF', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/302.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (44, 'CTEN', 'TENIS', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/303.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (45, 'DFUT', 'FUTBOL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/304.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (46, 'GBAL', 'BALONCESTO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/312.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (47, 'ARBOL', 'ARBOL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/300.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (48, 'PAPN', 'PAPA NOEL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/283.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (49, 'AZNE', 'AZUL / NEGRO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/111.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (50, 'MARO', 'MARINO / ROJO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/169.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (51, 'NANE', 'NARANJA / NEGRO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/181.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (52, 'AZBL', 'AZUL / BLANCO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/109.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (53, 'BLNG', 'BLANCO / NEGRO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/124.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (54, 'BLPL', 'BLANCO / PLATA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/263.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (55, 'TRAZU', 'TRASLUCIDO AZUL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/271.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (56, 'TRROJ', 'TRASLUCIDO ROJO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/276.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (57, 'FRA', 'FRANCIA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/229.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (58, 'ITA', 'ITALIA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/230.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (59, 'POR', 'PORTUGAL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/231.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (60, 'OSO', 'OSO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/197.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (61, 'BLGR', 'BLANCO / GRIS', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/121.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (62, 'NABL', 'NARANJA / BLANCO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/177.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (63, 'ROBL', 'ROJO / BLANCO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/211.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (64, 'VEBL', 'VERDE / BLANCO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/220.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (65, 'PIS', 'PISTACHO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/016.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (66, 'ATRO', 'TROFEO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/298.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (67, 'EATL', 'ATLETISMO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/305.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (68, 'FPAD', 'PADEL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/306.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (69, 'PLMT', 'PLATA MATE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/307.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (70, 'BLAM', 'BLANCO / AMARILLO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/118.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (71, 'GRNG', 'GRIS / NEGRO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/147.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (72, 'ESPB', 'ESPAÑA / BRONCE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/257.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (73, 'ESPO', 'ESPAÑA / ORO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/255.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (74, 'ESPP', 'ESPAÑA / PLATEADO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/256.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (75, 'ROBR', 'ROJO / BRONCE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/254.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (76, 'ROOR', 'ROJO / ORO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/252.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (77, 'ROPL', 'ROJO / PLATA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/253.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (78, 'APER', 'PERRO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/141.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (79, 'BGAT', 'GATO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/280.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (80, 'CCER', 'CERDO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/287.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (81, 'NEPL', 'NEGRO / PLATA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/269.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (82, 'TRAMA', 'TRASLUCIDO AMARILLO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/270.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (83, 'TRBLA', 'TRASLUCIDO BLANCO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/272.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (84, 'NENE', 'NEGRO / NEGRO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/297.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (85, 'ROMA', 'ROJO / MARINO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/212.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (86, 'VENE', 'VERDE / NEGRO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/224.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (87, 'VEO', 'VERDE OSCURO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/227.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (88, 'KAMA', 'KAKI / MARINO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/153.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (89, 'MAKA', 'MARINO / KAKI', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/164.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (90, 'FRESA', 'FRESA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/140.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (91, 'MANZA', 'MANZANA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/171.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (92, 'PERA', 'PERA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/209.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (93, 'TOMAT', 'TOMATE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/240.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (94, 'HRUG', 'RUGBY', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/313.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (95, 'CAMU', 'CAMUFALJE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/136.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (96, 'PTNO', 'PLATANO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/278.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (97, 'DOPL', 'DORADO / PLATEADO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/308.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (98, 'BLMA', 'BLANCO / MARINO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/122.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (99, 'TRFUC', 'TRASLUCIDO FUCSIA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/273.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (100, 'TRNAR', 'TRASLUCIDO NARANJA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/274.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (101, 'TRVER', 'TRASLUCIDO VERDE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/277.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (102, 'KIWI', 'KIWI', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/315.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (103, 'PIÑA', 'PIÑA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/260.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (104, 'UVA', 'UVA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/259.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (105, 'GRAM', 'GRIS / AMARILLO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/143.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (106, 'GRAZ', 'GRIS / AZUL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/144.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (107, 'GRRO', 'GRIS / ROJO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/148.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (108, 'GRVE', 'GRIS / VERDE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/149.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (109, 'AMBL', 'AMARILLO / BLANCO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/243.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (110, 'ROAM', 'ROJO / AMARILLO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/235.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (111, 'ESTR', 'ESTRELLA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/248.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (112, 'GRNA', 'GRIS / NARANJA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/146.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (113, 'PLAT', 'SILVER', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/009.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (114, 'ACOR', 'HEART', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/316.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (115, 'BGAF', 'SUNGLASS', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/317.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (116, 'CGUÑ', 'WINK', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/318.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (117, 'DSON', 'SMILE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/319.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (118, 'AMA', 'YELLOW', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/005.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (119, 'AZUL', 'BLUE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/019.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (120, 'NATU', 'NATURAL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/013.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (121, 'ROJ', 'RED', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/003.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (122, 'BLA', 'WHITE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/001.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (123, 'NEG', 'BLACK', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/002.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (124, 'VER', 'GREEN', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/004.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (125, 'NARA', 'ORANGE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/007.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (126, 'ROSA', 'PINK', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/022.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (127, 'MAR', 'NAVY BLUE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/006.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (128, 'FUCSI', 'FUCHSIA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/011.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (129, 'TRANS', 'TRANSPARENT', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/216.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (130, 'VEC', 'LIGHT GREEN', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/279.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (131, 'GRI', 'GREY', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/008.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (132, 'MARR', 'BROWN', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/018.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (133, 'AZC', 'LIGHT BLUE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/021.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (134, 'BUR', 'BURGUNDY', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/020.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (135, 'BEI', 'BEIGE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/117.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (136, 'KAK', 'KHAKI', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/014.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (137, 'ESP', 'SPAIN', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/139.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (138, 'BLAZ', 'WHITE / BLUE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/119.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (139, 'BLNA', 'WHITE / ORANGE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/123.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (140, 'BLRO', 'WHITE / RED', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/125.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (141, 'BLVE', 'WHITE / GREEN', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/126.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (142, 'DOR', 'GOLDEN', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/023.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (143, 'A', 'TYPE A', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/100.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (144, 'B', 'TYPE B', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/115.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (145, 'C', 'TYPE C', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/128.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (146, 'LIMA', 'LIME', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/284.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (147, 'MACL', 'LIGHT BROWN', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/162.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (148, 'MAOS', 'DARK BROWN', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/167.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (149, 'NGGR', 'BLACK/GREY', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/195.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (150, 'LIMON', 'LEMON', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/158.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (151, 'SAND', 'WATER MELON', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/261.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (152, 'AZR', 'ROYAL BLUE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/228.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (153, 'BLFU', 'WHITE / FUCSIA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/120.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (154, 'NEBL', 'BLACK/WHITE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/192.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (155, 'BGOL', 'GOLF', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/302.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (156, 'CTEN', 'TENIS', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/303.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (157, 'DFUT', 'SOCCER', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/304.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (158, 'GBAL', 'BASJET', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/312.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (159, 'ARBOL', 'TREE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/300.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (160, 'PAPN', 'NOEL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/283.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (161, 'AZNE', 'BLUE / BLACK', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/111.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (162, 'MARO', 'DARK BLUE / RED', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/169.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (163, 'NANE', 'ORANGE / BLACK', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/181.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (164, 'AZBL', 'BLUE / WHITE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/109.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (165, 'BLNG', 'WHITE / BLACK', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/124.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (166, 'BLPL', 'WHITE / SILVER', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/263.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (167, 'TRAZU', 'TRASLUCIDO BLUE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/271.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (168, 'TRROJ', 'TRASLUCIDO RED', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/276.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (169, 'FRA', 'FRANCE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/229.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (170, 'ITA', 'ITALY', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/230.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (171, 'POR', 'PORTUGAL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/231.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (172, 'OSO', 'BEAR', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/197.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (173, 'BLGR', 'WHITE / GREY', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/121.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (174, 'NABL', 'ORANGE / WHITE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/177.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (175, 'ROBL', 'RED / WHITE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/211.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (176, 'VEBL', 'GREEN / WHITE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/220.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (177, 'PIS', 'PISTACHIO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/016.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (178, 'ATRO', 'TROPHY', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/298.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (179, 'EATL', 'ATLETISM', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/305.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (180, 'FPAD', 'PADDLE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/306.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (181, 'PLMT', 'SILVER MAT', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/307.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (182, 'BLAM', 'WHITE / YELLOW', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/118.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (183, 'GRNG', 'GREY / BLACK', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/147.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (184, 'ESPB', 'SPAIN / BONRZE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/257.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (185, 'ESPO', 'SPAIN / GOLD', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/255.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (186, 'ESPP', 'SPAIN / SILVER', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/256.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (187, 'ROBR', 'RED / BRONZE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/254.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (188, 'ROOR', 'RED / GOLD', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/252.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (189, 'ROPL', 'RED / SILVER', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/253.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (190, 'APER', 'DOG', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/141.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (191, 'BGAT', 'CAT', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/280.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (192, 'CCER', 'PIG', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/287.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (193, 'NEPL', 'BLAC / SILVER', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/269.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (194, 'TRAMA', 'TRASLUCIDO YELLOW', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/270.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (195, 'TRBLA', 'TASLUCIDO WHITE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/272.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (196, 'NENE', 'BLACK / BLACK', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/297.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (197, 'ROMA', 'RED / DARK BLUE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/212.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (198, 'VENE', 'GREEN / BLACK', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/224.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (199, 'VEO', 'HUNTER', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/227.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (200, 'KAMA', 'KAKHI / DARK BLUE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/153.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (201, 'MAKA', 'DARK BLUE / KAKHI', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/164.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (202, 'FRESA', 'STRAWBERRY', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/140.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (203, 'MANZA', 'APPLE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/171.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (204, 'PERA', 'PERA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/209.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (205, 'TOMAT', 'TOMATO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/240.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (206, 'HRUG', 'RUGBY', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/313.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (207, 'CAMU', 'CAMOUFLAGE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/136.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (208, 'PTNO', 'BANANA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/278.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (209, 'DOPL', 'GOLD / SILVER', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/308.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (210, 'BLMA', 'WHITE / DARK BLUE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/122.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (211, 'TRFUC', 'TRASLUCIDO FUCSIA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/273.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (212, 'TRNAR', 'TRASLUCIDO ORANGE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/274.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (213, 'TRVER', 'TRASLUCIDO GREEN', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/277.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (214, 'KIWI', 'KIWI', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/315.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (215, 'PIÑA', 'ANANAS', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/260.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (216, 'UVA', 'GRAPE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/259.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (217, 'GRAM', 'GREY / YELLOW', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/143.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (218, 'GRAZ', 'GREY / BLUE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/144.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (219, 'GRRO', 'GREY / RED', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/148.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (220, 'GRVE', 'GREY / GREEN', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/149.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (221, 'AMBL', 'YELLOW / WHITE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/243.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (222, 'ROAM', 'RED / YELLOW', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/235.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (223, 'ESTR', 'STAR', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/248.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (224, 'GRNA', 'GREY / ORANGE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/146.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (225, 'CDEC', 'C / DECORACIÓN', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/326.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (226, 'CDEC', 'C / DECORATION', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/326.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (227, 'MROS', 'MARINO OSCURO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/333.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (228, 'MROS', 'DARK BLUE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/333.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (229, 'GROS', 'GRIS OSCURO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/372.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (230, 'GROS', 'DARK GREY', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/372.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (231, 'VEB', 'VERDE BOTELLA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/225.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (232, 'VEB', 'BOTTLE GREEN', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/225.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (233, 'ALE', 'ALEMANIA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/331.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (234, 'ALE', 'GERMANY', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/331.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (235, 'AND', 'ANDALUCIA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/330.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (236, 'AND', 'ANDALUSIA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/330.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (237, 'PIB', 'PAISES BAJOS', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/332.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (238, 'PIB', 'NETHERLANDS', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/332.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (239, 'MORA', 'MORADO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/174.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (240, 'MORA', 'PURPLE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/174.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (241, 'BARBR', 'B / ARBOL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/325.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (242, 'BARBR', 'B / TREE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/325.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (243, 'EPAT', 'E / PATO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/328.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (244, 'EPAT', 'E / PATO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/328.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (245, 'MUNI', 'MUÑECO NIEVE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/323.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (246, 'MUNI', 'SNOWMAN', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/323.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (247, 'OVA', 'OVALADO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/407.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (248, 'OVA', 'OVALED', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/407.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (249, 'RED', 'REDONDO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/406.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (250, 'RED', 'ROUND', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/406.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (251, 'NIEVE', 'NIEVE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/299.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (252, 'NIEVE', 'SNOW', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/299.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (253, 'GRCL', 'GRIS CLARO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/371.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (254, 'GRCL', 'LIGHT GREY', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/371.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (255, 'FVER', 'GREEN FLUOR', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/268.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (256, 'FVER', 'VERDE FLUOR', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/268.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (257, 'FNAR', 'NARANJA FLUOR', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/267.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (258, 'FNAR', 'FLUORO ORANGE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/267.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (259, 'FFUC', 'FLUORO FUCHSIA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/266.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (260, 'FFUC', 'FUCSIA FLUOR', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/266.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (261, 'FAMA', 'YELLOW FLUORO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/265.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (262, 'FAMA', 'AMARILLO FLUOR', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/265.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (263, 'ACIR', 'CIRCULO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/373.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (264, 'ACIR', 'CIRCLE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/373.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (265, 'CCUA', 'CUADRADO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/627.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (266, 'CCUA', 'SQUARED', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/627.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (267, 'BREC', 'RECTANGULO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/374.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (268, 'BREC', 'RECTANGLE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/374.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (269, 'GRNT', 'GRANATE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/431.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (270, 'GRNT', 'BURGUNDY', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/431.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (271, 'NARO', 'NARANJA OSCURO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/658.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (272, 'NARO', 'DARK ORANGE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/658.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (273, 'RENO', 'RENO', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/301.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (274, 'RENO', 'REINDEER', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/301.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (275, 'IELE', 'ELEFANTE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/369.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (276, 'IELE', 'ELEPHANT', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/369.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (277, 'JRAN', 'RANA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/370.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (278, 'JRAN', 'FROG', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/370.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (279, 'RAIN', 'RAINBOW', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/659.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (280, 'RAIN', 'RAINBOW', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/659.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (281, 'SALM', 'SALMON', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/660.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (282, 'SALM', 'SALMON', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/660.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (283, 'BEIGP', 'BEIG PASTEL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/661.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (284, 'ROSAP', 'ROSA PASTEL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/662.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (285, 'AZULP', 'AZUL PASTEL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/663.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (286, 'VERP', 'VERDE PASTEL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/664.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (287, 'AMAP', 'AMARILLO PASTEL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/665.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (288, 'BEIGP', 'BEIG PASTEL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/661.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (289, 'ROSAP', 'ROSA PASTEL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/662.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (290, 'AZULP', 'AZUL PASTEL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/663.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (291, 'VERP', 'VERDE PASTEL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/664.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (292, 'AMAP', 'AMARILLO PASTEL', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/665.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (293, 'BOLA', 'BOLA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/666.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (294, 'COCHE', 'COCHE', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/295.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (295, 'COCHE', 'CAR', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/295.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (296, 'CASA', 'CASA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/296.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (297, 'CASA', 'HOME', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/296.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (298, 'DONUTS', 'DONUTS', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/614.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (299, 'MOSTA', 'MOSTAZA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/483.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (300, 'MOSTA', 'MOSTAZA', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/483.png');
INSERT INTO grupoalan.colors (color_id, code, name, url) VALUES (301, 'DONUTS', 'DONUTS', 'https://makito.es/WebRoot/Store/Shops/Makito/MediaGallery/Color/614.png');
